server:
  port: 8080
  host: "0.0.0.0"
service:
  secretKey: "example"
database:
  host: "example"
  port: 5432
  user: "example"
  password: "example"
  name: "example"
  sslmode: "disable"
cloudinary:
  apiSecret: "example"
  apiKey: "example"
  folder: "example/"
  cloudName: "example"
cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:5173"
    - "http://localhost:5173"
  allow_credentials: true
